---
apiVersion: v1
kind: Service
metadata:
  name: sparkmaster
  namespace: spark
spec:
  ports:
  - name: master
    port: 7077
  - name: masterrest
    port: 6066
  - name: webui
    port: 8080
  - name: driverwebui
    port: 4040
  selector:
    app: spark
    component: sparkmaster
